# Generated by Django 6.0 on 2026-01-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
