# Generated by Django 6.0 on 2026-01-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
