# Generated by Django 6.0 on 2026-01-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(default='Our rental vehicles are well-maintained, reliable, and designed to give you a smooth and comfortable journey. \n                                 Whether you need a vehicle for daily travel, business trips, or weekend getaways, we offer flexible rental plans at affordable prices.\n                                 All vehicles are regularly serviced to ensure safety and performance.', max_length=150),
        ),
    ]
