# Generated by Django 6.0 on 2026-02-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_vehicle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(default='Our rental vehicles are well-maintained, reliable, and designed to give you a smooth and comfortable journey. \n                                 Whether you need a vehicle for daily travel, business trips, or weekend getaways, we offer flexible rental plans at affordable prices.\n                                 All vehicles are regularly serviced to ensure safety and performance.', max_length=5000),
        ),
    ]
